---
title: "Dashboard Proposal"
author: "Icíar Fernández Boyano"
date: "21/03/2020"
output: 
  html_document: 
    keep_md: yes
---

# A map to finding satisfaction in your PhD
#### *Data-driven sources of happiness in graduate school*

## Introduction 

This folder contains the requirements for Task #2 of Milestone 4. Detailed [instructions](https://stat545.stat.ubc.ca/evaluation/milestone_04/milestone_04/) on what is expected from this assignment are in the STAT547 website under [team projects](https://stat545.stat.ubc.ca/evaluation/projects/). Task #1 entails addressing student feedback on our project progress thus far, and is not in this folder.

## Description (~300 words)

Our app will have three "pages":

+ A **home** page that shows the different charts we have created for our dataset.

+ An **about** page that gives some information about its purpose and puts it into context.

+ A **contact** page if the user were to have any further questions.

The home page has two main parts:

1. A satisfaction section that plots the levels of satisfaction of students about their decision to start a PhD vs. now that they have started grad school. From a dropdown list, users will be able to explore how these levels of satisfaction change in relation to a few demographic variables, such as age or gender. 

2. A section that explores the relationships between student satisfaction currently (while in graduate school) in relation to other variables that we hypothesise may have an effect on satisfaction. The user will be able to explore these variables from a dropdown menu, which include supervisor relationship, PhD weekly hours, work-life balance... There will also be an option to visualize up to 2 variables at a time, i.e relationship between student satisfaction & supervisor relationship, coloured by work-life balance.

## Usage Scenario

Andi is a fourth year undergraduate student, and she is currently looking at her options to choose a graduate program. She has heard from multiple people that graduate school can be a great source of stress, and is unsure of what to look for in a supervisor / learning environment that will minimize this stress or at least provide ways to cope. Browsing the internet for resources and guides on how to do this, she finds our dashboard app. She is able to explore different variables that current graduate students have reported in relation to their satisfaction, and this gives her a clearer idea of what to look for when meeting potential supervisors or choosing a particular program. 

## Example sketch




